package rules

import "github.com/apkbugfinder/scanner/internal/types"

type Scope int

const (
	ScopeJava Scope = iota
	ScopeResourceXML
	ScopeManifest
	ScopeCertFiles
)

type Rule struct {
	ID                string
	Title             string
	Description       string
	MASVS             string
	CWE               string
	Category          string
	Severity          types.Severity
	Remediation       string
	Reference         string
	Scope             Scope
	Patterns          []string
	Regex             bool
	CaseInsensitive   bool
	OutputMustContain []string
	Absence           bool
	AbsenceSeverity   types.Severity
	CertExtensions    []string
}

const refStorage = "https://mobile-security.gitbook.io/masvs/security-requirements/0x07-v2-data_storage_and_privacy_requirements"
const refCrypto = "https://mobile-security.gitbook.io/masvs/security-requirements/0x08-v3-cryptography_requirements"
const refAuth = "https://mobile-security.gitbook.io/masvs/security-requirements/0x09-v4-authentication_and_session_management_requirements"
const refNetwork = "https://mobile-security.gitbook.io/masvs/security-requirements/0x10-v5-network_communication_requirements"
const refPlatform = "https://mobile-security.gitbook.io/masvs/security-requirements/0x11-v6-interaction_with_the_environment"
const refArch = "https://mobile-security.gitbook.io/masvs/security-requirements/0x06-v1-architecture_design_and_threat_modelling_requireme"
const refCode = "https://mobile-security.gitbook.io/masvs/security-requirements/0x12-v7-code_quality_and_build_setting_requirements"
const refResilience = "https://mobile-security.gitbook.io/masvs/security-requirements/0x15-v8-resiliency_against_reverse_engineering_requirements"

func All() []Rule {
	return []Rule{
		// V2 Storage
		{ID: "MSTG-STORAGE-2-SHAREDPREFS", Title: "Shared Preferences usage", MASVS: "MSTG-STORAGE-2", CWE: "CWE-922", Category: "Data Storage", Severity: types.SeverityMedium, Scope: ScopeJava, Patterns: []string{"getSharedPreferences("}, Remediation: "Ensure sensitive data in SharedPreferences is encrypted.", Reference: refStorage},
		{ID: "MSTG-STORAGE-2-SQLITE", Title: "SQLite Database usage", MASVS: "MSTG-STORAGE-2", CWE: "CWE-922", Category: "Data Storage", Severity: types.SeverityMedium, Scope: ScopeJava, Patterns: []string{"openOrCreateDatabase", "getWritableDatabase", "getReadableDatabase"}, Remediation: "Use parameterized queries and encrypt sensitive database content.", Reference: refStorage},
		{ID: "MSTG-STORAGE-2-FIREBASE", Title: "Firebase Database reference", MASVS: "MSTG-STORAGE-2", CWE: "CWE-200", Category: "Data Storage", Severity: types.SeverityMedium, Scope: ScopeJava, Patterns: []string{".firebaseio.com"}, Remediation: "Secure Firebase rules and avoid exposing sensitive data.", Reference: refStorage},
		{ID: "MSTG-STORAGE-2-REALM", Title: "Realm Database usage", MASVS: "MSTG-STORAGE-2", CWE: "CWE-200", Category: "Data Storage", Severity: types.SeverityMedium, Scope: ScopeJava, Patterns: []string{"RealmConfiguration"}, Remediation: "Encrypt Realm databases containing sensitive data.", Reference: refStorage},
		{ID: "MSTG-STORAGE-2-INTERNAL", Title: "Internal Storage usage", MASVS: "MSTG-STORAGE-2", CWE: "CWE-922", Category: "Data Storage", Severity: types.SeverityMedium, Scope: ScopeJava, Patterns: []string{"openFileOutput", "MODE_WORLD_READABLE", "MODE_WORLD_WRITEABLE", "FileInputStream"}, Remediation: "Avoid world-readable modes; encrypt sensitive files.", Reference: refStorage},
		{ID: "MSTG-STORAGE-2-EXTERNAL", Title: "External Storage access", MASVS: "MSTG-STORAGE-2", CWE: "CWE-922", Category: "Data Storage", Severity: types.SeverityMedium, Scope: ScopeJava, Patterns: []string{"getExternalFilesDir", "getExternalFilesDirs", "getExternalCacheDir", "getExternalCacheDirs", "getCacheDir", "getExternalStorageState", "getExternalStorageDirectory", "getExternalStoragePublicDirectory"}, Remediation: "Do not store sensitive data on external storage.", Reference: refStorage},
		{ID: "MSTG-STORAGE-2-TEMPFILE", Title: "Temporary File Creation", MASVS: "MSTG-STORAGE-2", CWE: "CWE-277", Category: "Data Storage", Severity: types.SeverityMedium, Scope: ScopeJava, Patterns: []string{".createTempFile("}, Remediation: "Set secure permissions on temporary files.", Reference: refStorage},
		{ID: "MSTG-PLATFORM-2-EDITOR", Title: "SharedPreferences.Editor usage", MASVS: "MSTG-PLATFORM-2", CWE: "CWE-922", Category: "Data Storage", Severity: types.SeverityLow, Scope: ScopeJava, Patterns: []string{"SharedPreferences.Editor"}, Remediation: "Validate input before persisting to SharedPreferences.", Reference: refPlatform},
		{ID: "MSTG-STORAGE-3-LOGS", Title: "Sensitive data in logs", MASVS: "MSTG-STORAGE-3", CWE: "CWE-532", Category: "Data Storage", Severity: types.SeverityMedium, Scope: ScopeJava, Patterns: []string{"Log.v(", "Log.d(", "Log.i(", "Log.w(", "Log.e(", "logger.log(", "logger.logp(", "log.info", "System.out.print", "System.err.print"}, Remediation: "Remove sensitive data from log statements in production.", Reference: refStorage},
		{ID: "MSTG-STORAGE-4-NOTIF", Title: "NotificationManager usage", MASVS: "MSTG-STORAGE-4", CWE: "CWE-829", Category: "Data Storage", Severity: types.SeverityLow, Scope: ScopeJava, Patterns: []string{"NotificationManager", ".setContentTitle(", ".setContentText("}, Remediation: "Avoid exposing sensitive data in notifications.", Reference: refStorage},
		{ID: "MSTG-STORAGE-5-KEYBOARD", Title: "Keyboard cache inputType", MASVS: "MSTG-STORAGE-5", CWE: "CWE-524", Category: "Data Storage", Severity: types.SeverityLow, Scope: ScopeJava, Patterns: []string{":inputType="}, Remediation: "Use appropriate inputType flags for sensitive fields.", Reference: refStorage},
		{ID: "MSTG-STORAGE-7-PASSWORD", Title: "Password inputType configured", MASVS: "MSTG-STORAGE-7", CWE: "CWE-359", Category: "Data Storage", Severity: types.SeverityInfo, Scope: ScopeJava, Patterns: []string{`:inputType="textPassword"`}, CaseInsensitive: true, Remediation: "Verify all sensitive fields use textPassword or equivalent.", Reference: refStorage},
		{ID: "MSTG-STORAGE-8-BACKUP", Title: "Application backup enabled", MASVS: "MSTG-STORAGE-8", CWE: "CWE-921", Category: "Data Storage", Severity: types.SeverityHigh, Scope: ScopeManifest, Patterns: []string{`android:allowBackup="true"`}, Remediation: "Set android:allowBackup=\"false\" or use encrypted backup.", Reference: refStorage},
		{ID: "MSTG-STORAGE-9-FLAGSECURE", Title: "FLAG_SECURE for screenshots", MASVS: "MSTG-STORAGE-9", CWE: "CWE-200", Category: "Data Storage", Severity: types.SeverityInfo, Scope: ScopeJava, Patterns: []string{"FLAG_SECURE"}, Remediation: "Use FLAG_SECURE on screens displaying sensitive data.", Reference: refStorage},
		{ID: "MSTG-STORAGE-10-FLUSH", Title: "Memory flush usage", MASVS: "MSTG-STORAGE-10", CWE: "CWE-316", Category: "Data Storage", Severity: types.SeverityInfo, Scope: ScopeJava, Patterns: []string{".flush("}, Remediation: "Clear sensitive data from memory after use.", Reference: refStorage},
		{ID: "MSTG-STORAGE-10-CLIPBOARD", Title: "ClipboardManager usage", MASVS: "MSTG-STORAGE-10", CWE: "CWE-316", Category: "Data Storage", Severity: types.SeverityMedium, Scope: ScopeJava, Patterns: []string{"ClipboardManager", ".setPrimaryClip(", "OnPrimaryClipChangedListener"}, Remediation: "Avoid copying sensitive data to clipboard.", Reference: refStorage},
		{ID: "MSTG-STORAGE-14-HARDCODE", Title: "Hard-coded sensitive strings", MASVS: "MSTG-STORAGE-14", CWE: "CWE-312", Category: "Secrets", Severity: types.SeverityHigh, Scope: ScopeJava, Regex: true, CaseInsensitive: true, Patterns: []string{`String (password|key|token|username|url|database|secret|bearer) = "`}, Remediation: "Remove hardcoded secrets; use Android Keystore.", Reference: refStorage},
		{ID: "MSTG-STORAGE-14-EMAIL", Title: "Hard-coded email addresses", MASVS: "MSTG-STORAGE-14", CWE: "CWE-312", Category: "Secrets", Severity: types.SeverityMedium, Scope: ScopeJava, Regex: true, Patterns: []string{`\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,6}\b`}, Remediation: "Remove hardcoded emails from source code.", Reference: refStorage},
		{ID: "MSTG-STORAGE-14-PRIVATEIP", Title: "Hard-coded private IP addresses", MASVS: "MSTG-STORAGE-14", CWE: "CWE-312", Category: "Secrets", Severity: types.SeverityMedium, Scope: ScopeJava, Regex: true, Patterns: []string{`(192\.168\.([0-9]|[0-9][0-9]|[0-2][0-5][0-5])\.([0-9]|[0-9][0-9]|[0-2][0-5][0-5]))|(172\.([1][6-9]|[2][0-9]|[3][0-1])\.([0-9]|[0-9][0-9]|[0-2][0-5][0-5])\.([0-9]|[0-9][0-9]|[0-2][0-5][0-5]))|(10\.([0-9]|[0-9][0-9]|[0-2][0-5][0-5])\.([0-9]|[0-9][0-9]|[0-2][0-5][0-5])\.([0-9]|[0-9][0-9]|[0-2][0-5][0-5]))`}, Remediation: "Avoid hardcoded internal network addresses.", Reference: refStorage},
		{ID: "MSTG-STORAGE-14-CLOUD", Title: "Hard-coded cloud URLs", MASVS: "MSTG-STORAGE-14", CWE: "CWE-312", Category: "Secrets", Severity: types.SeverityMedium, Scope: ScopeJava, Regex: true, Patterns: []string{`(\.amazonaws.com|\.(file|blob).core.windows.net|\.(storage|firebasestorage).googleapis.com)`}, Remediation: "Use secure configuration for cloud endpoints.", Reference: refStorage},
		{ID: "MSTG-STORAGE-14-BEGIN", Title: "Hard-coded PEM/certificate blocks", MASVS: "MSTG-STORAGE-14", CWE: "CWE-312", Category: "Secrets", Severity: types.SeverityCritical, Scope: ScopeJava, Patterns: []string{"-BEGIN "}, Remediation: "Remove embedded keys/certs; use Keystore.", Reference: refStorage},
		{ID: "MSTG-STORAGE-14-STRINGS", Title: "Hard-coded keys in strings.xml", MASVS: "MSTG-STORAGE-14", CWE: "CWE-312", Category: "Secrets", Severity: types.SeverityHigh, Scope: ScopeResourceXML, Regex: true, CaseInsensitive: true, Patterns: []string{`(_key"|_secret"|_token"|_client_id"|_api"|_debug"|_prod"|_stage")`}, Remediation: "Remove secrets from string resources.", Reference: refStorage},

		// V3 Crypto
		{ID: "MSTG-CRYPTO-1-SYMKEY", Title: "Hardcoded symmetric key material", MASVS: "MSTG-CRYPTO-1", CWE: "CWE-321", Category: "Cryptography", Severity: types.SeverityHigh, Scope: ScopeJava, Patterns: []string{"new SecretKeySpec(", " SecretKeySpec(", "new IvParameterSpec(", " IvParameterSpec("}, Remediation: "Generate keys via Android Keystore, not hardcoded bytes.", Reference: refCrypto},
		{ID: "MSTG-CRYPTO-4-HASH", Title: "Cryptographic hash/MAC usage", MASVS: "MSTG-CRYPTO-4", CWE: "CWE-327", Category: "Cryptography", Severity: types.SeverityMedium, Scope: ScopeJava, Patterns: []string{"Signature.getInstance", "MessageDigest.getInstance", "Mac.getInstance"}, Remediation: "Use SHA-256+ and avoid deprecated algorithms.", Reference: refCrypto},
		{ID: "MSTG-CRYPTO-3-CIPHER", Title: "Cipher.getInstance usage", MASVS: "MSTG-CRYPTO-3", CWE: "CWE-649", Category: "Cryptography", Severity: types.SeverityMedium, Scope: ScopeJava, Patterns: []string{"Cipher.getInstance"}, Remediation: "Use AES/GCM; avoid ECB and weak modes.", Reference: refCrypto},
		{ID: "MSTG-CRYPTO-3-STATICIV", Title: "Static IV / hardcoded byte array", MASVS: "MSTG-CRYPTO-3", CWE: "CWE-1204", Category: "Cryptography", Severity: types.SeverityHigh, Scope: ScopeJava, Regex: true, Patterns: []string{`byte\s*\[\s*\]\s*\w+\s*=\s*\{`, `new\s+byte\s*\[\s*\]\s*\{`, `\{0,\s*0,`}, Remediation: "Use random IVs per encryption operation.", Reference: refCrypto},
		{ID: "MSTG-CRYPTO-6-RANDOM", Title: "Weak random number generation", MASVS: "MSTG-CRYPTO-6", CWE: "CWE-330", Category: "Cryptography", Severity: types.SeverityMedium, Scope: ScopeJava, Patterns: []string{"new Random(", "SHA1PRNG", "Dual_EC_DRBG"}, Remediation: "Use SecureRandom for security-sensitive operations.", Reference: refCrypto},

		// V4 Auth
		{ID: "MSTG-AUTH-2-COOKIES", Title: "Cookie/WebView session handling", MASVS: "MSTG-AUTH-2", CWE: "CWE-359", Category: "Authentication", Severity: types.SeverityMedium, Scope: ScopeJava, CaseInsensitive: true, Patterns: []string{" setAcceptThirdPartyCookies(", "setCookie(", "CookieManager", "findViewById(", "setWebViewClient("}, Remediation: "Secure cookie handling in WebViews.", Reference: refAuth},
		{ID: "MSTG-AUTH-8-BIOMETRIC", Title: "Biometric authentication usage", MASVS: "MSTG-AUTH-8", CWE: "CWE-287", Category: "Authentication", Severity: types.SeverityInfo, Scope: ScopeJava, Patterns: []string{"BiometricPrompt", "BiometricManager", "FingerprintManager"}, Remediation: "Verify biometric implementation follows best practices.", Reference: refAuth},
		{ID: "MSTG-AUTH-8-BIOINVALID", Title: "Biometric key invalidation", MASVS: "MSTG-AUTH-8", CWE: "CWE-287", Category: "Authentication", Severity: types.SeverityInfo, Scope: ScopeJava, Patterns: []string{".setInvalidatedByBiometricEnrollment("}, Remediation: "Invalidate keys when biometric enrollment changes.", Reference: refAuth},

		// V5 Network
		{ID: "MSTG-NETWORK-1-MITM", Title: "Insecure SSL/TLS trust configuration", MASVS: "MSTG-NETWORK-1", CWE: "CWE-319", Category: "Network", Severity: types.SeverityHigh, Scope: ScopeJava, CaseInsensitive: true, Patterns: []string{"SSLCertificateSocketFactory.getInsecure(", "TrustAllHostnameVerifier", "ALLOW_ALL_HOSTNAME_VERIFIER", "NullHostnameVerifier", "checkServerTrusted", "X509TrustManager"}, OutputMustContain: []string{"Trust", "Hostname", "Insecure", "checkServerTrusted"}, Remediation: "Use HTTPS with proper certificate validation.", Reference: refNetwork},
		{ID: "MSTG-NETWORK-2-WEAKTLS", Title: "Weak SSL/TLS protocol configuration", MASVS: "MSTG-NETWORK-2", CWE: "CWE-326", Category: "Network", Severity: types.SeverityHigh, Scope: ScopeJava, CaseInsensitive: true, Patterns: []string{"SSLContext.getInstance(", "tlsVersions(TlsVersion"}, OutputMustContain: []string{"tls", "SSL"}, Remediation: "Enforce TLS 1.2+ minimum.", Reference: refNetwork},
		{ID: "MSTG-NETWORK-2-CLEARTEXT", Title: "Cleartext traffic permitted", MASVS: "MSTG-NETWORK-2", CWE: "CWE-319", Category: "Network", Severity: types.SeverityHigh, Scope: ScopeManifest, Patterns: []string{`android:usesCleartextTraffic="true"`, `cleartextTrafficPermitted="true"`}, Remediation: "Disable cleartext traffic globally.", Reference: refNetwork},
		{ID: "MSTG-NETWORK-3-SERVERCERT", Title: "Custom server certificate validation", MASVS: "MSTG-NETWORK-3", CWE: "CWE-295", Category: "Network", Severity: types.SeverityMedium, Scope: ScopeJava, CaseInsensitive: true, Patterns: []string{"X509Certificate", "checkServerTrusted(", "checkClientTrusted(", "getAcceptedIssuers("}, OutputMustContain: []string{"checkServerTrusted", "checkClientTrusted", "getAcceptedIssuers", "X509Certificate"}, Remediation: "Verify certificate chain properly; avoid trust-all implementations.", Reference: refNetwork},
		{ID: "MSTG-NETWORK-3-WEBVIEWSSL", Title: "WebView SSL error handler", MASVS: "MSTG-NETWORK-3", CWE: "CWE-295", Category: "Network", Severity: types.SeverityHigh, Scope: ScopeJava, CaseInsensitive: true, Patterns: []string{"onReceivedSslError", "sslErrorHandler", ".proceed(", "setWebViewClient", "findViewById"}, OutputMustContain: []string{"onReceivedSslError"}, Remediation: "Call handler.cancel() on SSL errors; never blindly proceed.", Reference: refNetwork},
		{ID: "MSTG-NETWORK-3-HOSTNAME", Title: "Hostname verification bypass", MASVS: "MSTG-NETWORK-3", CWE: "CWE-297", Category: "Network", Severity: types.SeverityHigh, Scope: ScopeJava, CaseInsensitive: true, Patterns: []string{".setHostnameVerifier(", ".setDefaultHostnameVerifier(", "NullHostnameVerifier", "ALLOW_ALL_HOSTNAME_VERIFIER", "AllowAllHostnameVerifier", "NO_VERIFY", "implements HostnameVerifier"}, OutputMustContain: []string{"HostnameVerifier", "setHostnameVerifier", "ALLOW_ALL", "NullHostname", "NO_VERIFY"}, Remediation: "Use default hostname verification.", Reference: refNetwork},
		{ID: "MSTG-NETWORK-4-CERTFILES", Title: "Hard-coded certificate/keystore files", MASVS: "MSTG-NETWORK-4", CWE: "CWE-295", Category: "Network", Severity: types.SeverityHigh, Scope: ScopeCertFiles, CertExtensions: []string{".cer", ".pem", ".cert", ".crt", ".pub", ".key", ".pfx", ".p12", ".der", ".jks", ".bks"}, Remediation: "Do not bundle private keys/certs in the APK.", Reference: refNetwork},
		{ID: "MSTG-NETWORK-4-PINSET", Title: "Certificate pinning (pin-set)", MASVS: "MSTG-NETWORK-4", CWE: "CWE-295", Category: "Network", Severity: types.SeverityInfo, Scope: ScopeResourceXML, Patterns: []string{"<pin-set"}, Remediation: "Verify pinning covers all sensitive endpoints.", Reference: refNetwork},
		{ID: "MSTG-NETWORK-4-PINNER", Title: "Certificate pinning implementation", MASVS: "MSTG-NETWORK-4", CWE: "CWE-295", Category: "Network", Severity: types.SeverityInfo, Scope: ScopeJava, Patterns: []string{"certificatePinner", "KeyStore.getInstance", "trustManagerFactory", "Retrofit.Builder(", "Picasso.Builder("}, OutputMustContain: []string{"certificatePinner", "KeyStore.getInstance", "trustManagerFactory", "Builder("}, Remediation: "Pin endpoint certificates or public keys.", Reference: refNetwork},
		{ID: "MSTG-NETWORK-4-TRUSTUSER", Title: "Custom user trust anchors", MASVS: "MSTG-NETWORK-4", CWE: "CWE-295", Category: "Network", Severity: types.SeverityHigh, Scope: ScopeResourceXML, Patterns: []string{`<certificates src="user"`}, Remediation: "Avoid trusting user-installed CAs for sensitive traffic.", Reference: refNetwork},
		{ID: "MSTG-NETWORK-6-PROVIDER", Title: "Security Provider (ProviderInstaller)", MASVS: "MSTG-NETWORK-6", CWE: "CWE-693", Category: "Network", Severity: types.SeverityInfo, Scope: ScopeJava, Patterns: []string{" ProviderInstaller.installIfNeeded", " ProviderInstaller.installIfNeededAsync"}, Absence: true, AbsenceSeverity: types.SeverityMedium, Remediation: "Call ProviderInstaller.installIfNeeded to update security provider.", Reference: refNetwork},

		// V6 Platform
		{ID: "MSTG-PLATFORM-1-PERMS", Title: "Permissions declared", MASVS: "MSTG-PLATFORM-1", CWE: "CWE-276", Category: "Platform", Severity: types.SeverityInfo, Scope: ScopeResourceXML, Regex: true, Patterns: []string{`<uses-permission|<permission`}, Remediation: "Review protectionLevel for custom permissions.", Reference: refPlatform},
		{ID: "MSTG-PLATFORM-1-DEPRECATED", Title: "Deprecated permissions", MASVS: "MSTG-PLATFORM-1", CWE: "CWE-276", Category: "Platform", Severity: types.SeverityMedium, Scope: ScopeResourceXML, Regex: true, Patterns: []string{`BIND_CARRIER_MESSAGING_SERVICE|BIND_CHOOSER_TARGET_SERVICE|GET_TASKS|PERSISTENT_ACTIVITY|PROCESS_OUTGOING_CALLS|READ_INPUT_STATE|RESTART_PACKAGES|SET_PREFERRED_APPLICATIONS|SMS_FINANCIAL_TRANSACTIONS|USE_FINGERPRINT|UNINSTALL_SHORTCUT`}, Remediation: "Remove deprecated permission usage.", Reference: refPlatform},
		{ID: "MSTG-PLATFORM-1-CUSTPERM", Title: "Custom permission checks in code", MASVS: "MSTG-PLATFORM-1", CWE: "CWE-276", Category: "Platform", Severity: types.SeverityInfo, Scope: ScopeJava, Patterns: []string{"checkCallingOrSelfPermission", "checkSelfPermission"}, OutputMustContain: []string{"checkCallingOrSelfPermission", "checkSelfPermission"}, Remediation: "Enforce permissions in manifest, not only in code.", Reference: refPlatform},
		{ID: "MSTG-PLATFORM-2-SQLI", Title: "Potential SQL Injection", MASVS: "MSTG-PLATFORM-2", CWE: "CWE-89", Category: "Platform", Severity: types.SeverityHigh, Scope: ScopeJava, Patterns: []string{".rawQuery(", ".execSQL(", "appendWhere("}, Remediation: "Use parameterized queries.", Reference: refPlatform},
		{ID: "MSTG-PLATFORM-2-XSS", Title: "Potential Cross-Site Scripting", MASVS: "MSTG-PLATFORM-2", CWE: "CWE-79", Category: "Platform", Severity: types.SeverityHigh, Scope: ScopeJava, Patterns: []string{".evaluateJavascript(", `.loadUrl("javascript:`}, OutputMustContain: []string{"javascript", "evaluateJavascript"}, Remediation: "Encode output; avoid injecting untrusted JS.", Reference: refPlatform},
		{ID: "MSTG-PLATFORM-2-RCE", Title: "OS command execution", MASVS: "MSTG-PLATFORM-2", CWE: "CWE-78", Category: "Platform", Severity: types.SeverityHigh, Scope: ScopeJava, Patterns: []string{`Runtime.getRuntime().exec(`, `new ProcessBuilder(`}, Remediation: "Avoid Runtime.exec with untrusted input.", Reference: refPlatform},
		{ID: "MSTG-PLATFORM-2-FRAGMENT", Title: "Fragment Injection (PreferenceActivity)", MASVS: "MSTG-PLATFORM-2", CWE: "CWE-470", Category: "Platform", Severity: types.SeverityHigh, Scope: ScopeJava, Patterns: []string{"extends PreferenceActivity"}, Remediation: "Implement isValidFragment or target SDK 19+.", Reference: refPlatform},
		{ID: "MSTG-PLATFORM-2-SAFEBROWSE", Title: "EnableSafeBrowsing configured", MASVS: "MSTG-PLATFORM-2", CWE: "CWE-940", Category: "Platform", Severity: types.SeverityInfo, Scope: ScopeResourceXML, Patterns: []string{"EnableSafeBrowsing"}, Remediation: "Enable SafeBrowsing for WebViews.", Reference: refPlatform},
		{ID: "MSTG-PLATFORM-2-URLLOAD", Title: "URL Loading in WebViews", MASVS: "MSTG-PLATFORM-2", CWE: "CWE-939", Category: "Platform", Severity: types.SeverityMedium, Scope: ScopeJava, Patterns: []string{"shouldOverrideUrlLoading(", "shouldInterceptRequest("}, Remediation: "Validate URLs in WebView handlers.", Reference: refPlatform},
		{ID: "MSTG-PLATFORM-3-URLSCHEME", Title: "Custom URL Schemes", MASVS: "MSTG-PLATFORM-3", CWE: "CWE-939", Category: "Platform", Severity: types.SeverityMedium, Scope: ScopeResourceXML, Patterns: []string{"android:scheme"}, Remediation: "Validate custom URL scheme handlers.", Reference: refPlatform},
		{ID: "MSTG-PLATFORM-4-BROADCAST", Title: "Implicit intents for broadcast", MASVS: "MSTG-PLATFORM-4", CWE: "CWE-927", Category: "Platform", Severity: types.SeverityMedium, Scope: ScopeJava, Patterns: []string{"sendBroadcast(", "sendOrderedBroadcast(", "sendStickyBroadcast("}, OutputMustContain: []string{"sendBroadcast(", "sendOrderedBroadcast(", "sendStickyBroadcast("}, Remediation: "Use explicit intents or LocalBroadcastManager.", Reference: refPlatform},
		{ID: "MSTG-PLATFORM-4-ACTIVITY", Title: "Implicit intents for activity", MASVS: "MSTG-PLATFORM-4", CWE: "CWE-927", Category: "Platform", Severity: types.SeverityMedium, Scope: ScopeJava, Patterns: []string{"startActivity(", "startActivityForResult("}, OutputMustContain: []string{"startActivity(", "startActivityForResult("}, Remediation: "Use explicit intents with setComponent/setPackage.", Reference: refPlatform},
		{ID: "MSTG-PLATFORM-5-JS", Title: "JavaScript enabled in WebView", MASVS: "MSTG-PLATFORM-5", CWE: "CWE-749", Category: "Platform", Severity: types.SeverityMedium, Scope: ScopeJava, CaseInsensitive: true, Patterns: []string{"setJavaScriptEnabled(", "WebView"}, OutputMustContain: []string{"setJavaScriptEnabled"}, Remediation: "Disable JS unless strictly required.", Reference: refPlatform},
		{ID: "MSTG-PLATFORM-6-LOADURL", Title: "Remote/Local URL load in WebViews", MASVS: "MSTG-PLATFORM-6", CWE: "CWE-940", Category: "Platform", Severity: types.SeverityMedium, Scope: ScopeJava, Patterns: []string{".loadUrl(", ".loadDataWithBaseURL("}, Remediation: "Allowlist URLs loaded in WebViews.", Reference: refPlatform},
		{ID: "MSTG-PLATFORM-6-HARDLINK", Title: "Hard-coded links", MASVS: "MSTG-PLATFORM-6", CWE: "CWE-200", Category: "Platform", Severity: types.SeverityLow, Scope: ScopeJava, Patterns: []string{"://"}, Remediation: "Review hardcoded URLs for sensitive endpoints.", Reference: refPlatform},
		{ID: "MSTG-PLATFORM-6-FILEACCESS", Title: "WebView file access permissions", MASVS: "MSTG-PLATFORM-6", CWE: "CWE-749", Category: "Platform", Severity: types.SeverityHigh, Scope: ScopeJava, Patterns: []string{"setAllowFileAccess(", "setAllowFileAccessFromFileURLs(", "setAllowUniversalAccessFromFileURLs(", "setAllowContentAccess("}, Remediation: "Disable file access in WebView settings.", Reference: refPlatform},
		{ID: "MSTG-PLATFORM-6-WEBDEBUG", Title: "Remote WebView debugging enabled", MASVS: "MSTG-PLATFORM-6", CWE: "CWE-215", Category: "Platform", Severity: types.SeverityHigh, Scope: ScopeJava, Patterns: []string{`setWebContentsDebuggingEnabled(`}, Remediation: "Disable WebView debugging in production.", Reference: refPlatform},
		{ID: "MSTG-PLATFORM-7-JSINTERFACE", Title: "JavaScript interface exposed", MASVS: "MSTG-PLATFORM-7", CWE: "CWE-749", Category: "Platform", Severity: types.SeverityHigh, Scope: ScopeJava, Patterns: []string{"addJavascriptInterface("}, Remediation: "Avoid JS bridges; validate URLs if required.", Reference: refPlatform},
		{ID: "MSTG-PLATFORM-8-SERIALIZE", Title: "Object serialization/deserialization", MASVS: "MSTG-PLATFORM-8", CWE: "CWE-502", Category: "Platform", Severity: types.SeverityMedium, Scope: ScopeJava, Patterns: []string{".getSerializable(", ".getSerializableExtra(", "new Gson()"}, OutputMustContain: []string{"getSerializable", "Gson"}, Remediation: "Avoid deserializing untrusted data.", Reference: refPlatform},
		{ID: "MSTG-PLATFORM-10-WCLEANUP", Title: "WebView cleanup", MASVS: "MSTG-PLATFORM-10", CWE: "CWE-200", Category: "Platform", Severity: types.SeverityInfo, Scope: ScopeJava, Patterns: []string{`.clearCache(`, `.deleteAllData(`, `.removeAllCookies(`, `.deleteRecursively(`, `.clearFormData(`}, Absence: true, AbsenceSeverity: types.SeverityLow, Remediation: "Clear WebView cache/cookies after sensitive sessions.", Reference: refPlatform},

		// V1 Arch
		{ID: "MSTG-ARCH-9-UPDATE", Title: "App update mechanism (AppUpdateManager)", MASVS: "MSTG-ARCH-9", CWE: "CWE-1277", Category: "Architecture", Severity: types.SeverityInfo, Scope: ScopeJava, Patterns: []string{" AppUpdateManager"}, Remediation: "Force security updates via AppUpdateType.IMMEDIATE.", Reference: refArch},
		{ID: "MSTG-ARCH-9-SIDELOAD", Title: "Third-party APK installation", MASVS: "MSTG-ARCH-9", CWE: "CWE-940", Category: "Architecture", Severity: types.SeverityHigh, Scope: ScopeJava, Patterns: []string{`.setDataAndType(`, `application/vnd.android.package-archive`, "FileProvider", "getFileDirPath(", "installApp("}, OutputMustContain: []string{"vnd.android.package-archive"}, Remediation: "Install updates via Google Play only.", Reference: refArch},

		// V7 Code
		{ID: "MSTG-CODE-2-DEBUGGABLE", Title: "Debuggable application", MASVS: "MSTG-CODE-2", CWE: "CWE-215", Category: "Code Quality", Severity: types.SeverityCritical, Scope: ScopeManifest, Patterns: []string{`android:debuggable="true"`}, Remediation: "Set android:debuggable=\"false\" in release builds.", Reference: refCode},
		{ID: "MSTG-CODE-4-STRICTMODE", Title: "StrictMode enabled", MASVS: "MSTG-CODE-4", CWE: "CWE-749", Category: "Code Quality", Severity: types.SeverityMedium, Scope: ScopeJava, Patterns: []string{"StrictMode.setThreadPolicy", "StrictMode.setVmPolicy"}, Remediation: "Disable StrictMode in production.", Reference: refCode},
		{ID: "MSTG-CODE-6-EXCEPTION", Title: "Exception handling patterns", MASVS: "MSTG-CODE-6", CWE: "CWE-755", Category: "Code Quality", Severity: types.SeverityLow, Scope: ScopeJava, Patterns: []string{` RuntimeException("`, "UncaughtExceptionHandler("}, OutputMustContain: []string{"Exception"}, Remediation: "Handle exceptions without exposing sensitive data.", Reference: refCode},
		{ID: "MSTG-CODE-9-OBFUSC", Title: "Code obfuscation indicators", MASVS: "MSTG-CODE-9", CWE: "CWE-693", Category: "Code Quality", Severity: types.SeverityInfo, Scope: ScopeJava, Patterns: []string{"package com.a.", "import com.a.", "class a$b"}, Absence: true, AbsenceSeverity: types.SeverityLow, Remediation: "Enable ProGuard/R8 obfuscation for release builds.", Reference: refCode},

		// V8 Resilience
		{ID: "MSTG-RESILIENCE-1-ROOT", Title: "Root detection", MASVS: "MSTG-RESILIENCE-1", CWE: "CWE-250", Category: "Resilience", Severity: types.SeverityInfo, Scope: ScopeJava, Patterns: []string{"supersu", "superuser", "/xbin/", "/sbin/"}, OutputMustContain: []string{"super", "bin/"}, Absence: true, AbsenceSeverity: types.SeverityLow, Remediation: "Implement multiple root detection methods.", Reference: refResilience},
		{ID: "MSTG-RESILIENCE-2-ANTIDEBUG", Title: "Anti-debugging detection", MASVS: "MSTG-RESILIENCE-2", CWE: "CWE-693", Category: "Resilience", Severity: types.SeverityInfo, Scope: ScopeJava, Patterns: []string{" isDebuggable", "isDebuggerConnected"}, OutputMustContain: []string{"Debug"}, Absence: true, AbsenceSeverity: types.SeverityLow, Remediation: "Implement anti-debugging checks.", Reference: refResilience},
		{ID: "MSTG-RESILIENCE-3-INTEGRITY", Title: "File integrity checks", MASVS: "MSTG-RESILIENCE-3", CWE: "CWE-693", Category: "Resilience", Severity: types.SeverityInfo, Scope: ScopeJava, Patterns: []string{`.getEntry("classes`}, OutputMustContain: []string{"classes"}, Absence: true, AbsenceSeverity: types.SeverityLow, Remediation: "Implement CRC/signature integrity checks.", Reference: refResilience},
		{ID: "MSTG-RESILIENCE-5-EMULATOR", Title: "Emulator detection", MASVS: "MSTG-RESILIENCE-5", CWE: "CWE-693", Category: "Resilience", Severity: types.SeverityInfo, Scope: ScopeJava, Regex: true, Patterns: []string{`Build\.MODEL\.contains\(|Build\.MANUFACTURER\.contains\(|Build\.HARDWARE\.contains\(|Build\.PRODUCT\.contains\(|/genyd`}, OutputMustContain: []string{"Build", "genyd"}, Absence: true, AbsenceSeverity: types.SeverityLow, Remediation: "Implement emulator detection.", Reference: refResilience},
		{ID: "MSTG-RESILIENCE-7-SAFETYNET", Title: "SafetyNet / defence mechanisms", MASVS: "MSTG-RESILIENCE-7", CWE: "CWE-693", Category: "Resilience", Severity: types.SeverityInfo, Scope: ScopeJava, Patterns: []string{"SafetyNetClient "}, Absence: true, AbsenceSeverity: types.SeverityLow, Remediation: "Consider Play Integrity / SafetyNet attestation.", Reference: refResilience},
	}
}
